### ISSUE TITLE
Add link to FAQs to classifiction interface

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/BHL#29]
The moderators have completed the FAQs, and Jules will be continuing to update them regularly.

http://talk.sciencegossip.org/#/boards/BSC0000005/discussions/DSC00000wh

Could we add a prominent link on the Science Gossip classification page, as with Higgs Hunters?

**Comment by eatyourgreens** [comment]
We should open the FAQ page in a new tab, so that they don't lose the classification they're working on.
http://talk.sciencegossip.org/#/boards/BSC0000009/discussions/DSC000010v?page=1&comment_id=5518228a40ead526f6000004
'Return to classifying' from Talk will still reload the page in the same tab as Talk, loading a new page to classify. I don't think we can do much about that, short of implementing an OWD-style cache that stores unfinished classifications, so I guess we'll rely on the volunteers to remember to go back to their original tab from Talk.

**Comment by DarrenMcRoy** [comment]
I like that, sure! Whenever we can!
